# Generated by Django 6.0.6 on 2026-07-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='youtube_trailer_id',
            field=models.CharField(help_text='Example: dQw4w9WgXcQ', max_length=1000),
        ),
    ]
