# Generated by Django 6.0.6 on 2026-07-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0002_alter_movie_youtube_trailer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='youtube_trailer_id',
        ),
        migrations.AddField(
            model_name='movie',
            name='youtube_trailer_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
