# Generated by Django 6.0.6 on 2026-07-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0008_alter_review_created_at_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='is_bo0ked',
            new_name='is_booked',
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
